# Generated by Django 4.2.16 on 2024-11-22 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('create_date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
