# Generated by Django 4.2.16 on 2024-11-22 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscribers_subscribe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='subscribe_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
